import Vue from "vue";

export default async ({ app }, inject) => {
  var state = {
    activeColor: "#ffffff",
    tool: "add",
    activeFormat: "CSS",
    activeExport: "web",
    activeConfig: "grid",
    activeShape: "cube",
    hoveredArea: "◆",
    csvOutput: "",
    jsonOutput: "",
    cssOutput: "",
    htmlOutput: "",
    facets: 0,
    voxelLength: 0,
    size: 0,
    drag: false,
    dragMap: false,
    dragFile: false,
    showWalls: true,
    hideGrid: false,
    hideFloor: false,
    openMenu: false,
    invert: 1,
    leftPanel: true,
    rightPanel: true,
    loading: true,
    saving: false,
    saved: false,
    walls: {
      t: false,
      b: true,
      bl: true,
      br: true,
      fl: false,
      fr: false,
    },
    offsets: {
      t: [0, 0, 1],
      b: [0, 0, -1],
      fr: [0, 1, 0],
      fl: [1, 0, 0],
      bl: [0, -1, 0],
      br: [-1, 0, 0],
      f: [0, 0, 0]
    },
    voxelFaces: ['t', 'b', 'br', 'bl', 'fl', 'fr'],
    zoom: 0.6,
    tilt: 0,
    pan: 0,
    rotX: 65,
    rotY: 45,
    cols: 16,
    rows: 16,
    voxels: Array.from({ length: 12 }, () => ({})),
    cache: null,
    history: [],
    redoStack: [],
    sceneTransform: {
      isometric: "translateZ(0) translateY(100px) rotateX(65deg) rotate(45deg)",
      flat: "translateZ(100px) rotate(90deg)",
      frontLeft: "translateZ(1800px) rotateX(65deg)",
      frontRight: "translateZ(1800px) rotateX(65deg) rotate(90deg)",
    },
    textures: [
      "dirt2",
      "dirt",
      "ice3",
      "glass",
      "brick",
      "brick2",
      "brick3",
      "wood",
      "dirt4",
      "rock",
      "wood4",
      "wood3",
      "rock3",
      "rock6",
      "rock7",
      "rock4",
      "rock5",
      "dirt6",
      "grass3",
      "wood5",
      "mine5",
      "mine6",
      "mine4",
      "mine",
      "mine7",
      "ice",
      "cacti",
      "ice2",
      "dirt3",
      "rock2",
      "mine3",
      "sand",

    ],
    colors: [
      "#be4a2f",
      "#d77643",
      "#ead4aa",
      "#e4a672",
      "#b86f50",
      "#733e39",
      "#3e2731",
      "#a22633",
      "#e43b44",
      "#f77622",
      "#feae34",
      "#fee761",
      "#63c74d",
      "#3e8948",
      "#265c42",
      "#193c3e",
      "#124e89",
      "#0099db",
      "#2ce8f5",
      "#ffffff",
      "#c0cbdc",
      "#8b9bb4",
      "#5a6988",
      "#3a4466",
      "#262b44",
      "#181425",
      "#ff0044",
      "#68386c",
      "#b55088",
      "#f6757a",
      "#e8b796",
      "#c28569",
    ],

  };

  inject("ctx", Vue.observable(state));
};
